server:
  port: 8020
spring:
  application:
    name: menu
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/Delicious
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lly116902
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true